### ISSUE TITLE
prh_predictor2 has an R construct in matlab

### ISSUE THREAD

**Issue by spluque** [stacyderuiter/TagTools#15]
There seems to be an R construct in the matlab/octave code here:

https://github.com/stacyderuiter/TagTools/blob/8103e08101c12bad0a515578fdc731aedfcb831b/matlab/processing/prh_predictor2.m#L116

Below is likely the intention:

```matlab
V(k) = norm(std(A(ks, :)));
```

**Comment by stacyderuiter** [comment]
Hi Sebastian, Thanks for pointing this out.

It is odd, but I don't see how it can actually be an R construct as the person who wrote this function has never opened R (to my knowledge). So it's hard to understand how it got there. 

Whatever happened, it wasn't desirable, and I've corrected it as you suggested (today in commit 9036a146). Thanks again.

**Comment by spluque** [comment]
Thanks for the quick response, Stacy.  Looks like a copy-paste error.  The double colon is used in R to access a particular namespace, and Octave definitely don't use it (I don't use Matlab).  It took some debugging to find it.
