### ISSUE TITLE
Package ‘tagtools’ is not available for new versions of R

### ISSUE THREAD

**Issue by DNachtsheim** [stacyderuiter/TagTools#29]
Hi all, 

I have received a new computer and have installed a recent version of R (R 4.2.1). When setting up my new R, I also wanted to install the TagTools Package as I'm working frequently with DTAG data in R. 

When calling install.packages("tagtools"), I received the message: package ‘tagtools’ is not available for this version of R. 

When trying to download from GitHub, I received the message: ERROR: dependency 'hht' is not available for package 'tagtools'
Might this be the problematic package? How may I be able to install tagtools?

I'm looking forward to a solution! 

Best
Dominik Nachtsheim

**Comment by stacyderuiter** [comment]
Thanks for flagging this! I had just realized it a few days ago but haven't had time to work on it yet. I will try to do so ASAP. The package isn't on CRAN, so won't ever work via install.packages(), but I plan to fix the hhr dependency issue as soon as I can.

**Comment by stacyderuiter** [comment]
Also we're trying to transition to https://github.com/animaltags/tagtools_r but haven't taken this personal page down yet. I don't think it'll fix the issue but for future reference

**Comment by DNachtsheim** [comment]
Thanks for the quick response and the details! 👍 Looking forward to see it working again :-)

**Comment by stacyderuiter** [comment]
The hht dependency is now removed and installation should be possible from the "new" repo location: [https://github.com/animaltags/tagtools_r](https://github.com/animaltags/tagtools_r ) I will shortly remove the files from this (no longer maintained) repo and update the readme to redirect users to the new "home" of the tag tools.
